// src/svelte/Config.svelte
<script>
  import {appData} from './store/appData'
</script>

<h2>config</h2>

<h3>appData</h3>

<ul>
  <li>isPackaged: {$appData.isPackaged}</li>
</ul>

<h3>pathes</h3>

<ul>
  <li>home: {$appData.pathes.home}</li>
  <li>userData: {$appData.pathes.userData}</li>
  <li>exe: {$appData.pathes.exe}</li>
  <li>module: {$appData.pathes.module}</li>
  <li>current: {$appData.pathes.current}</li>
</ul>

// src/react/Config.tsx
import AppData from '../libs/AppData'

export default (): JSX.Element => {
  return (
    <div>
      <h3>appData</h3>
      <ul>
        <li>isPackaged: {AppData.data.isPackaged}</li>
      </ul>

      <h4>appData pathes</h4>
      <ul>
        <li>current: {AppData.data.pathes.current}</li>
        <li>exe: {AppData.data.pathes.exe}</li>
        <li>home: {AppData.data.pathes.home}</li>
        <li>module: {AppData.data.pathes.module}</li>
        <li>userData: {AppData.data.pathes.userData}</li>
      </ul>
    </div>
  )
}
